import type { Locale } from "@/lib/site-content";

export const companyProfile = {
  id: {
    heroEyebrow: "PROFIL PERUSAHAAN 2026",
    heroTitle: "Mitra tepercaya untuk layanan operasional dan collection.",
    heroDescription:
      "PT Pelita Anugrah Perkasa membantu klien mencapai tujuan bisnis melalui proses yang efisien, tim kompeten, dan komitmen untuk memberikan hasil terbaik.",
    heroVisualLabel: "LAYANAN PROFESIONAL",
    heroVisualTitle: "Profesionalisme dan kepercayaan",
    employeeStat: "100+",
    employeeLabel: "karyawan profesional",
    certificationStat: "SPPI · AFPI",
    certificationLabel: "sertifikasi tim",
    aboutEyebrow: "TENTANG PERUSAHAAN",
    aboutTitle: "Layanan operasional yang profesional dan terukur.",
    aboutBody:
      "PT Pelita Anugrah Perkasa adalah perusahaan outsourcing yang berfokus pada layanan desk collection serta penyediaan tenaga kerja profesional (labor supply). Didukung oleh lebih dari 100 karyawan bersertifikasi SPPI dan AFPI, kami membantu mitra mengelola dan menagih piutang secara profesional, efektif, dan sesuai ketentuan yang berlaku.",
    aboutBodySecondary:
      "Dengan mengedepankan integritas, komunikasi yang humanis, dan standar operasional yang terukur, kami menyediakan solusi yang aman, terpercaya, dan berorientasi pada hasil. Tenaga kerja kami yang kompeten dan terlatih mendukung produktivitas bisnis klien dari berbagai sektor.",
    visionTitle: "Visi",
    vision:
      "Menyediakan layanan outsourcing sumber daya manusia yang profesional dan menjadi mitra yang andal serta terpercaya bagi klien.",
    missionTitle: "Misi",
    missions: [
      "Mengembangkan sumber daya manusia yang andal dan profesional.",
      "Menyediakan layanan penagihan yang berorientasi pada target.",
      "Memberikan komitmen dan nilai terbaik kepada seluruh pihak yang bekerja sama dengan PT Pelita Anugrah Perkasa.",
      "Mendorong dan meningkatkan inklusi keuangan melalui praktik penagihan yang etis dan sesuai peraturan.",
    ],
    valuesTitle: "Nilai perusahaan",
    values: [
      { name: "Integritas", description: "Menjunjung kejujuran, tanggung jawab, dan etika kerja dalam setiap proses serta hubungan dengan klien maupun debitur." },
      { name: "Profesionalisme", description: "Bekerja dengan standar tinggi, disiplin, berorientasi pada hasil terukur, dan sesuai regulasi industri keuangan." },
      { name: "Inovasi", description: "Mengembangkan sistem, strategi, dan teknologi penagihan yang adaptif untuk meningkatkan efektivitas dan efisiensi." },
      { name: "Kolaborasi", description: "Membangun kerja sama yang kuat antara tim internal, mitra, dan klien untuk mencapai tujuan bersama." },
      { name: "Berorientasi pada hasil", description: "Berfokus pada pencapaian hasil nyata dan berkelanjutan untuk mendukung pertumbuhan bisnis klien." },
    ],
    servicesTitle: "Layanan kami",
    services: [
      { name: "Desk Collection Services", description: "Penagihan melalui telepon oleh tim profesional bersertifikat dengan komunikasi persuasif dan humanis, untuk menjaga hubungan baik dan mendorong pembayaran tepat waktu sesuai etika serta ketentuan OJK dan AFPI." },
      { name: "Collection Management & Monitoring", description: "Manajemen aktivitas collection yang mencakup perencanaan strategi, pelaporan harian, pengawasan performa, dan analisis tingkat keberhasilan penagihan." },
      { name: "Data Management & Reporting System", description: "Sistem pemantauan dan pelaporan berbasis data yang memberi klien visibilitas dan kendali atas aktivitas penagihan." },
      { name: "Labor Supply", description: "Penyediaan tenaga kerja profesional yang telah melalui proses seleksi secara cepat, fleksibel, dan efisien untuk berbagai kebutuhan operasional. Kami mengutamakan kualitas, kedisiplinan, dan produktivitas tenaga kerja; pengalaman kerja sama mencakup Polytron dan Indodana." },
    ],
    processTitle: "Alur desk collection",
    processIntro: "Alur kerja desk collection, kriteria account, indikator, dan proses tindak lanjut.",
    assignmentTitle: "New Assignment → Review Collection Management Service → Campaign → Desk Collection",
    deskCollectionTarget: "Target: ACR 300–500 per hari; 150 panggilan keluar per hari.",
    farmerTitle: "DC Farmer",
    farmerCriteria: "Kriteria: Maintain Account, Payment Slip, Nature Payment, Last Payment Date T, Reschedule Account.",
    hunterTitle: "DC Hunter",
    hunterCriteria: "Kriteria: New Account Valid, Acc Valid New PTP, Tracer Not Pay, Low Risk, Medium & High Risk Valid Acc, serta Acc Broken dari DC Farmer.",
    negotiation: "Negosiasi",
    prospect: "Prospek → Promise to Pay (PTP) → Keep Promise.",
    notProspect: "Tidak prospek → Segmented Account.",
    segmentedTitle: "Segmented Account",
    segmentedCriteria: "Parameter: perilaku pembayaran 5 bulan terakhir, keterjangkauan pelanggan, lokasi alamat, LPO 1/2/3, dan tanggal pembayaran terakhir.",
    lowRisk: "Low Risk",
    highRisk: "High Risk — area jauh dari cakupan FC atau belum memiliki FC, tidak ada pembayaran dalam 5 bulan, dan saldo besar.",
    skipTracer: "Skip Tracer",
    skipMethods: "Metode: riwayat panggilan, media sosial, kontak darurat, kolega dan keluarga, informasi dari kantor klien, serta menghubungi melalui aplikasi atau mencari kontak.",
    validContact: "Kontak valid: pembayaran; atau tanpa pembayaran (RTP/refuse to pay, broken promise, atau masalah keuangan).",
    invalidContact: "Kontak tidak valid atau tidak terhubung.",
    fieldEscalation: "Account tanpa pembayaran serta account yang tidak valid/tidak terhubung berlanjut ke Internal Field Collection.",
    internalField: "Internal Field Collection",
    fieldMetrics: [
      "Pelaporan dan pelacakan GPS melalui aplikasi seluler.",
      "ACR maksimal 150.",
      "Rencana kunjungan aktivitas harian; 12–15 kunjungan per hari.",
      "Pemetaan area FC dan prioritas saldo besar.",
      "Karakter berdasarkan riwayat dan LPO (tanggal pembayaran terakhir).",
    ],
    systemsTitle: "System Collection Kami (Desk Collection Pro)",
    systemsIntro: "Dua sistem utama mendukung efektivitas proses penagihan:",
    systems: [
      { name: "Predictive Call System", description: "Sistem otomatis yang melakukan panggilan secara berurutan dan efisien untuk meningkatkan produktivitas serta tingkat kontak agent." },
      { name: "Manual Call System", description: "Panggilan manual untuk kasus yang membutuhkan pendekatan personal, fleksibel, dan komunikasi persuasif." },
    ],
    systemsClosing: "Kombinasi keduanya mendukung proses penagihan yang cepat, akurat, dan tetap humanis.",
    clientsTitle: "Klien kami",
    clients: [
      "Traveloka",
      "PT Teknologi Internasional Nusantara (TIN)",
      "Bussan Auto Finance (BAF)",
      "Akulaku",
      "Kreditplus (PT KB Finansia Multi Finance)",
      "MOFI",
      "BCA",
      "Polytron",
      "Bank Neo Commerce",
      "BFI Finance",
    ],
    certificationTitle: "ISO/IEC 27001:2022",
    certificationEyebrow: "INTERNATIONAL CERTIFICATE OF REGISTRATION",
    certificationSummary: "Sistem manajemen keamanan informasi, keamanan siber, dan perlindungan privasi PT Pelita Anugrah Perkasa telah dinilai secara independen dan memenuhi persyaratan ISO/IEC 27001:2022.",
    certificationCommitment: "Sertifikasi ini mencerminkan komitmen terhadap standar kualitas internasional. Perusahaan menyatakan prosesnya dijalankan secara efisien, transparan, dan sesuai peraturan untuk mendukung kepercayaan dan kepuasan klien dalam pengelolaan aset.",
    certificationScope: "Sales Outsourcing, Operational Outsourcing, Human Resource Outsourcing, dan Collection Outsourcing (SoA-PAP Rev. 00).",
    certificationAddress: "Jalan Pondok Kelapa Raya Blok D9, Kel. Pondok Kelapa, Kec. Duren Sawit, Jakarta Timur, DKI Jakarta 13450, Indonesia.",
    certificateNumber: "240207003249270001",
    initialAssessment: "31 Januari 2024",
    registrationDate: "7 Februari 2024",
    surveillanceOne: "7 Januari 2025",
    surveillanceTwo: "7 Januari 2026",
    recertification: "6 Februari 2027",
    expiryDate: "6 Februari 2027",
    officesTitle: "Kantor kami",
    offices: [
      { name: "Kantor 1 — Malang", address: "Jl. Sudimoro No. 17–18, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur." },
      { name: "Kantor 2 — Yogyakarta", address: "Idea Zone Lantai 5, Jl. Magelang No. 188, Karangwaru, Kec. Tegalrejo, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55242." },
    ],
    contactTitle: "Mari bekerja sama",
    contactBody: "Kemitraan yang kuat menciptakan kesuksesan berkelanjutan. Dengan profesionalisme, integritas, dan inovasi, kami siap mendukung bisnis Anda mencapai kinerja optimal dan pertumbuhan berkelanjutan. Mari bekerja sama—kesuksesan Anda adalah misi kami.",
    contactPerson: "Ahimsa — Direktur",
    phone: "+62 821-4371-3602",
    email: "callcenter@papcorp.services",
    primaryWebsiteLabel: "Situs web",
    secondaryWebsiteLabel: "Situs web lain yang dicantumkan dalam profil",
    secondaryWebsite: "www.papcorporation.com",
    learnMore: "Pelajari lebih lanjut",
    contactCta: "Hubungi kami",
    sourceFootnote: "Informasi profil perusahaan bersumber dari Company Profile 2026.",
  },
  en: {
    heroEyebrow: "COMPANY PROFILE 2026",
    heroTitle: "A trusted partner for operational and collection services.",
    heroDescription:
      "PT Pelita Anugrah Perkasa helps clients achieve business goals through efficient processes, capable teams and a strong commitment to results.",
    heroVisualLabel: "PROFESSIONAL SERVICES",
    heroVisualTitle: "Professionalism and trust",
    employeeStat: "100+",
    employeeLabel: "professional employees",
    certificationStat: "SPPI · AFPI",
    certificationLabel: "team certifications",
    aboutEyebrow: "ABOUT THE COMPANY",
    aboutTitle: "Professional, measurable operational services.",
    aboutBody:
      "PT Pelita Anugrah Perkasa is an outsourcing company focused on desk collection services and professional labor supply. Supported by more than 100 employees certified by SPPI and AFPI, we help partners manage and collect receivables professionally, effectively and in accordance with applicable regulations.",
    aboutBodySecondary:
      "With integrity, human-centered communication and measured operating standards, we provide secure, trusted and results-oriented solutions. Our competent, trained workforce supports client productivity across industries.",
    visionTitle: "Vision",
    vision:
      "To provide professional human-resource outsourcing services and become a reliable, trusted partner to our clients.",
    missionTitle: "Mission",
    missions: [
      "Develop a reliable and professional workforce.",
      "Provide target-oriented collection services.",
      "Deliver commitment and value to everyone working with PT Pelita Anugrah Perkasa.",
      "Encourage and improve financial inclusion through ethical collection practices that comply with applicable regulations.",
    ],
    valuesTitle: "Our values",
    values: [
      { name: "Integrity", description: "Uphold honesty, responsibility and work ethics in every process and relationship with clients and debtors." },
      { name: "Professionalism", description: "Work to high standards, with discipline and measurable results, in line with financial-industry regulations." },
      { name: "Innovation", description: "Develop adaptive collection systems, strategies and technology to improve effectiveness and efficiency." },
      { name: "Collaboration", description: "Build strong cooperation among internal teams, partners and clients to achieve shared goals." },
      { name: "Result-oriented", description: "Focus on tangible, sustainable outcomes that support client business growth." },
    ],
    servicesTitle: "Our services",
    services: [
      { name: "Desk Collection Services", description: "Telephone-based collection by a certified professional team using persuasive, human-centered communication to maintain relationships and encourage timely payment in line with OJK and AFPI ethics and requirements." },
      { name: "Collection Management & Monitoring", description: "End-to-end management of collection activities, including strategy planning, daily reporting, performance supervision and collection performance analysis." },
      { name: "Data Management & Reporting System", description: "Data-based monitoring and reporting systems that give clients visibility and control over collection activities." },
      { name: "Labor Supply", description: "Fast, flexible and efficient supply of screened professional personnel for varied operational needs. We prioritize workforce quality, discipline and productivity; experience includes cooperation with Polytron and Indodana." },
    ],
    processTitle: "Desk collection workflow",
    processIntro: "Desk collection workflow, account criteria, indicators and follow-up process.",
    assignmentTitle: "New Assignment → Review Collection Management Service → Campaign → Desk Collection",
    deskCollectionTarget: "Target: ACR 300–500 per day; 150 outbound calls per day.",
    farmerTitle: "DC Farmer",
    farmerCriteria: "Criteria: Maintain Account, Payment Slip, Nature Payment, Last Payment Date T and Reschedule Account.",
    hunterTitle: "DC Hunter",
    hunterCriteria: "Criteria: New Account Valid, Acc Valid New PTP, Tracer Not Pay, Low Risk, Medium & High Risk Valid Acc, and Acc Broken from DC Farmer.",
    negotiation: "Negotiation",
    prospect: "Prospect → Promise to Pay (PTP) → Keep Promise.",
    notProspect: "Not prospect → Segmented Account.",
    segmentedTitle: "Segmented Account",
    segmentedCriteria: "Parameters: payment behavior over the last 5 months, customer reachability, address location, LPO 1/2/3 and last payment date.",
    lowRisk: "Low Risk",
    highRisk: "High Risk — area far from field-collection (FC) coverage or without an FC, no payment within 5 months, and a large balance.",
    skipTracer: "Skip Tracer",
    skipMethods: "Methods: call history, social media, emergency contacts, colleagues and family, information from the client office, and calling through an application or finding contact details.",
    validContact: "Valid contact: payment; or no payment (RTP/refuse to pay, broken promise, or financial problem).",
    invalidContact: "Invalid contact or unable to reach.",
    fieldEscalation: "Accounts with no payment and accounts that are invalid or unreachable proceed to Internal Field Collection.",
    internalField: "Internal Field Collection",
    fieldMetrics: [
      "Reporting and GPS tracking through a mobile application.",
      "Maximum ACR of 150.",
      "Daily visit activity plan; 12–15 visits per day.",
      "FC area mapping and priority for large balances.",
      "Character based on history and LPO (last payment date).",
    ],
    systemsTitle: "Our Collection System (Desk Collection Pro)",
    systemsIntro: "Two main systems support collection effectiveness:",
    systems: [
      { name: "Predictive Call System", description: "An automated system that places calls sequentially and efficiently, increasing agent productivity and contact rates." },
      { name: "Manual Call System", description: "Manual calls for cases requiring a personal, flexible approach and persuasive communication." },
    ],
    systemsClosing: "Together, these systems support a fast, accurate and human-centered collection process.",
    clientsTitle: "Our clients",
    clients: [
      "Traveloka",
      "PT Teknologi Internasional Nusantara (TIN)",
      "Bussan Auto Finance (BAF)",
      "Akulaku",
      "Kreditplus (PT KB Finansia Multi Finance)",
      "MOFI",
      "BCA",
      "Polytron",
      "Bank Neo Commerce",
      "BFI Finance",
    ],
    certificationTitle: "ISO/IEC 27001:2022",
    certificationEyebrow: "INTERNATIONAL CERTIFICATE OF REGISTRATION",
    certificationSummary: "The information security management, cybersecurity and privacy protection system of PT Pelita Anugrah Perkasa was independently assessed and found to meet ISO/IEC 27001:2022 requirements.",
    certificationCommitment: "The certification reflects a commitment to international quality standards. The company states that its processes are carried out efficiently, transparently and in accordance with regulations to support client trust and satisfaction in asset management.",
    certificationScope: "Sales Outsourcing, Operational Outsourcing, Human Resource Outsourcing and Collection Outsourcing (SoA-PAP Rev. 00).",
    certificationAddress: "Jalan Pondok Kelapa Raya Blok D9, Kel. Pondok Kelapa, Kec. Duren Sawit, East Jakarta, DKI Jakarta 13450, Indonesia.",
    certificateNumber: "240207003249270001",
    initialAssessment: "31 January 2024",
    registrationDate: "7 February 2024",
    surveillanceOne: "7 January 2025",
    surveillanceTwo: "7 January 2026",
    recertification: "6 February 2027",
    expiryDate: "6 February 2027",
    officesTitle: "Our offices",
    offices: [
      { name: "Office 1 — Malang", address: "Jl. Sudimoro No. 17–18, Mojolangu, Lowokwaru, Malang, East Java." },
      { name: "Office 2 — Yogyakarta", address: "Idea Zone, 5th Floor, Jl. Magelang No. 188, Karangwaru, Tegalrejo, Yogyakarta City, Special Region of Yogyakarta 55242." },
    ],
    contactTitle: "Let’s work together",
    contactBody: "Strong partnerships create sustainable success. With professionalism, integrity and innovation as our foundation, we are ready to help your business achieve optimal performance and sustainable growth. Let’s work together—your success is our mission.",
    contactPerson: "Ahimsa — Director",
    phone: "+62 821-4371-3602",
    email: "callcenter@papcorp.services",
    primaryWebsiteLabel: "Website",
    secondaryWebsiteLabel: "Other website listed in the profile",
    secondaryWebsite: "www.papcorporation.com",
    learnMore: "Learn more",
    contactCta: "Contact us",
    sourceFootnote: "Company profile information is based on the approved 2026 company profile.",
  },
} as const;

export type ProfileContent = (typeof companyProfile)[Locale];
